*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:16:27 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x13937b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13937b0 pid: 9151 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9151)
spawned uWSGI worker 1 (pid: 9153, cores: 8)
spawned uWSGI worker 2 (pid: 9154, cores: 8)
spawned uWSGI worker 3 (pid: 9155, cores: 8)
spawned uWSGI worker 4 (pid: 9156, cores: 8)
spawned uWSGI worker 5 (pid: 9157, cores: 8)
spawned uWSGI worker 6 (pid: 9176, cores: 8)
spawned uWSGI worker 7 (pid: 9184, cores: 8)
spawned uWSGI worker 8 (pid: 9202, cores: 8)
Sat Jun 23 06:16:42 2018 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:16:46 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0xe767b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe767b0 pid: 9227 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9227)
spawned uWSGI worker 1 (pid: 9229, cores: 8)
spawned uWSGI worker 2 (pid: 9230, cores: 8)
spawned uWSGI worker 3 (pid: 9231, cores: 8)
spawned uWSGI worker 4 (pid: 9232, cores: 8)
spawned uWSGI worker 5 (pid: 9233, cores: 8)
spawned uWSGI worker 6 (pid: 9234, cores: 8)
spawned uWSGI worker 7 (pid: 9235, cores: 8)
spawned uWSGI worker 8 (pid: 9242, cores: 8)
Sat Jun 23 06:17:13 2018 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:17:17 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0xaf77b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaf77b0 pid: 9304 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9304)
spawned uWSGI worker 1 (pid: 9306, cores: 8)
spawned uWSGI worker 2 (pid: 9307, cores: 8)
spawned uWSGI worker 3 (pid: 9308, cores: 8)
spawned uWSGI worker 4 (pid: 9309, cores: 8)
spawned uWSGI worker 5 (pid: 9310, cores: 8)
spawned uWSGI worker 6 (pid: 9311, cores: 8)
spawned uWSGI worker 7 (pid: 9342, cores: 8)
spawned uWSGI worker 8 (pid: 9343, cores: 8)
DAMN ! worker 8 (pid: 9343) died :( trying respawn ...
Respawned uWSGI worker 8 (new pid: 9381)
DAMN ! worker 8 (pid: 9381) died :( trying respawn ...
Respawned uWSGI worker 8 (new pid: 9390)
...brutally killing workers...
Sat Jun 23 06:20:51 2018 - received message 0 from emperor
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/pangestoe-server/socket.sock)
running /var/www/html/pangestoe-server/venv/bin/uwsgi
*** has_emperor mode detected (fd: 5) ***
[uWSGI] getting INI configuration from /var/www/html/pangestoe-server/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:20:52 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x17d4740
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x17d4740 pid: 9304 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 9304)
spawned uWSGI worker 1 (pid: 9507, cores: 8)
spawned uWSGI worker 2 (pid: 9508, cores: 8)
spawned uWSGI worker 3 (pid: 9509, cores: 8)
spawned uWSGI worker 4 (pid: 9510, cores: 8)
spawned uWSGI worker 5 (pid: 9511, cores: 8)
spawned uWSGI worker 6 (pid: 9526, cores: 8)
spawned uWSGI worker 7 (pid: 9527, cores: 8)
spawned uWSGI worker 8 (pid: 9528, cores: 8)
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:29:46 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x9497b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x9497b0 pid: 1660 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1660)
spawned uWSGI worker 1 (pid: 1662, cores: 8)
spawned uWSGI worker 2 (pid: 1663, cores: 8)
spawned uWSGI worker 3 (pid: 1664, cores: 8)
spawned uWSGI worker 4 (pid: 1665, cores: 8)
spawned uWSGI worker 5 (pid: 1680, cores: 8)
spawned uWSGI worker 6 (pid: 1681, cores: 8)
spawned uWSGI worker 7 (pid: 1697, cores: 8)
spawned uWSGI worker 8 (pid: 1698, cores: 8)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1698|app: 0|req: 1/1] 50.82.183.122 () {42 vars in 655 bytes} [Sat Jun 23 06:29:51 2018] GET / => generated 0 bytes in 44 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1698|app: 0|req: 2/2] 50.82.183.122 () {42 vars in 632 bytes} [Sat Jun 23 06:29:52 2018] GET /nginx-logo.png => generated 0 bytes in 18 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1698|app: 0|req: 3/3] 50.82.183.122 () {42 vars in 630 bytes} [Sat Jun 23 06:29:52 2018] GET /poweredby.png => generated 0 bytes in 18 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 2)
...brutally killing workers...
Sat Jun 23 06:30:09 2018 - received message 0 from emperor
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/pangestoe-server/socket.sock)
running /var/www/html/pangestoe-server/venv/bin/uwsgi
*** has_emperor mode detected (fd: 5) ***
[uWSGI] getting INI configuration from /var/www/html/pangestoe-server/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:30:10 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x1838740
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1838740 pid: 1660 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1660)
spawned uWSGI worker 1 (pid: 1780, cores: 8)
spawned uWSGI worker 2 (pid: 1781, cores: 8)
spawned uWSGI worker 3 (pid: 1782, cores: 8)
spawned uWSGI worker 4 (pid: 1783, cores: 8)
spawned uWSGI worker 5 (pid: 1784, cores: 8)
spawned uWSGI worker 6 (pid: 1806, cores: 8)
spawned uWSGI worker 7 (pid: 1819, cores: 8)
spawned uWSGI worker 8 (pid: 1820, cores: 8)
[uwsgi-signal] read(): Connection reset by peer [core/signal.c line 480]
Sat Jun 23 06:30:14 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 5 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 5 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 6 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 6 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 7 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 7 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 8 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sat Jun 23 06:30:14 2018 - uWSGI worker 8 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:30:41 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0xb83820
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xb83820 pid: 752 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 752)
spawned uWSGI worker 1 (pid: 910, cores: 8)
spawned uWSGI worker 2 (pid: 911, cores: 8)
spawned uWSGI worker 3 (pid: 914, cores: 8)
spawned uWSGI worker 4 (pid: 915, cores: 8)
spawned uWSGI worker 5 (pid: 922, cores: 8)
spawned uWSGI worker 6 (pid: 923, cores: 8)
spawned uWSGI worker 7 (pid: 946, cores: 8)
spawned uWSGI worker 8 (pid: 955, cores: 8)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 955|app: 0|req: 1/1] 50.82.183.122 () {42 vars in 655 bytes} [Sat Jun 23 06:32:06 2018] GET / => generated 0 bytes in 46 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 955|app: 0|req: 2/2] 50.82.183.122 () {42 vars in 632 bytes} [Sat Jun 23 06:32:06 2018] GET /nginx-logo.png => generated 0 bytes in 27 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 1)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 955|app: 0|req: 3/3] 50.82.183.122 () {42 vars in 630 bytes} [Sat Jun 23 06:32:06 2018] GET /poweredby.png => generated 0 bytes in 24 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 2)
...brutally killing workers...
Sat Jun 23 06:33:30 2018 - received message 0 from emperor
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/pangestoe-server/socket.sock)
running /var/www/html/pangestoe-server/venv/bin/uwsgi
*** has_emperor mode detected (fd: 5) ***
[uWSGI] getting INI configuration from /var/www/html/pangestoe-server/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:33:31 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x1b297b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1b297b0 pid: 752 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 752)
spawned uWSGI worker 1 (pid: 1637, cores: 8)
spawned uWSGI worker 2 (pid: 1638, cores: 8)
spawned uWSGI worker 3 (pid: 1639, cores: 8)
spawned uWSGI worker 4 (pid: 1661, cores: 8)
spawned uWSGI worker 5 (pid: 1662, cores: 8)
spawned uWSGI worker 6 (pid: 1663, cores: 8)
spawned uWSGI worker 7 (pid: 1666, cores: 8)
spawned uWSGI worker 8 (pid: 1667, cores: 8)
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:33:42 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x268f7b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x268f7b0 pid: 1705 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1705)
spawned uWSGI worker 1 (pid: 1707, cores: 8)
spawned uWSGI worker 2 (pid: 1708, cores: 8)
spawned uWSGI worker 3 (pid: 1709, cores: 8)
spawned uWSGI worker 4 (pid: 1710, cores: 8)
spawned uWSGI worker 5 (pid: 1711, cores: 8)
spawned uWSGI worker 6 (pid: 1712, cores: 8)
spawned uWSGI worker 7 (pid: 1732, cores: 8)
spawned uWSGI worker 8 (pid: 1733, cores: 8)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1733|app: 0|req: 1/1] 50.82.183.122 () {42 vars in 655 bytes} [Sat Jun 23 06:33:48 2018] GET / => generated 0 bytes in 27 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1733|app: 0|req: 3/3] 50.82.183.122 () {42 vars in 632 bytes} [Sat Jun 23 06:33:48 2018] GET /nginx-logo.png => generated 0 bytes in 42 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 1)
[pid: 1733|app: 0|req: 3/3] 50.82.183.122 () {42 vars in 630 bytes} [Sat Jun 23 06:33:48 2018] GET /poweredby.png => generated 0 bytes in 45 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 2)
Traceback (most recent call last):
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/pangestoe-server/src/app.py", line 14, in initialize_database
    Database.initialize()
  File "/var/www/html/pangestoe-server/src/common/database.py", line 12, in initialize
    Database.DATABASE = client.get_default_database()
  File "/var/www/html/pangestoe-server/venv/lib/python3.6/site-packages/pymongo/mongo_client.py", line 943, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined
[pid: 1733|app: 0|req: 4/4] 110.78.145.194 () {28 vars in 331 bytes} [Sat Jun 23 06:38:24 2018] HEAD / => generated 0 bytes in 21 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 3)
...brutally killing workers...
Sat Jun 23 06:40:33 2018 - received message 0 from emperor
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/pangestoe-server/socket.sock)
running /var/www/html/pangestoe-server/venv/bin/uwsgi
*** has_emperor mode detected (fd: 5) ***
[uWSGI] getting INI configuration from /var/www/html/pangestoe-server/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:40:34 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
*** Starting uWSGI 2.0.17 (64bit) on [Sat Jun 23 06:47:02 2018] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 23 June 2018 02:58:06
os: Linux-2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018
nodename: pangestoe-server
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/pangestoe-server/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3896
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/pangestoe-server/socket.sock fd 3
Python version: 3.6.5 (default, Jun 23 2018, 02:20:49)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
Set PythonHome to /var/www/html/pangestoe-server/venv
Python main interpreter initialized at 0x21ce7b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/pangestoe-server/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x21ce7b0 pid: 2108 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2108)
spawned uWSGI worker 1 (pid: 2110, cores: 8)
spawned uWSGI worker 2 (pid: 2111, cores: 8)
spawned uWSGI worker 3 (pid: 2112, cores: 8)
spawned uWSGI worker 4 (pid: 2113, cores: 8)
spawned uWSGI worker 5 (pid: 2114, cores: 8)
spawned uWSGI worker 6 (pid: 2115, cores: 8)
spawned uWSGI worker 7 (pid: 2116, cores: 8)
spawned uWSGI worker 8 (pid: 2117, cores: 8)
[pid: 2117|app: 0|req: 1/1] 50.82.183.122 () {42 vars in 655 bytes} [Sat Jun 23 06:47:16 2018] GET / => generated 6794 bytes in 51 msecs (HTTP/1.1 200) 4 headers in 196 bytes (1 switches on core 6)
announcing my loyalty to the Emperor...
[pid: 2117|app: 0|req: 3/2] 50.82.183.122 () {42 vars in 712 bytes} [Sat Jun 23 06:47:16 2018] GET /static/css/style.css => generated 2242 bytes in 15 msecs via sendfile() (HTTP/1.1 200) 8 headers in 303 bytes (0 switches on core 1)
[pid: 2117|app: 0|req: 3/3] 50.82.183.122 () {42 vars in 716 bytes} [Sat Jun 23 06:47:16 2018] GET /static/css/gallery.css => generated 2479 bytes in 3 msecs via sendfile() (HTTP/1.1 200) 8 headers in 303 bytes (0 switches on core 2)
[pid: 2117|app: 0|req: 5/4] 50.82.183.122 () {42 vars in 719 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/logo_placeholder.png => generated 2010890 bytes in 26 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (18 switches on core 3)
[pid: 2117|app: 0|req: 5/5] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/1/Pangestoe-32.jpg => generated 15247103 bytes in 64 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (156 switches on core 4)
[pid: 2117|app: 0|req: 9/6] 50.82.183.122 () {42 vars in 713 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/1/Pangestoe-3.jpg => generated 5570240 bytes in 31 msecs via sendfile() (HTTP/1.1 200) 8 headers in 296 bytes (58 switches on core 5)
[pid: 2117|app: 0|req: 9/7] 50.82.183.122 () {42 vars in 713 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/1/Pangestoe-2.jpg => generated 6061895 bytes in 51 msecs via sendfile() (HTTP/1.1 200) 8 headers in 296 bytes (62 switches on core 0)
[pid: 2117|app: 0|req: 9/8] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/1/Pangestoe-38.jpg => generated 7400066 bytes in 61 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (77 switches on core 6)
[pid: 2117|app: 0|req: 9/9] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:47:17 2018] GET /static/img/1/Pangestoe-35.jpg => generated 8184620 bytes in 72 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (85 switches on core 7)
[pid: 2117|app: 0|req: 10/10] 50.82.183.122 () {40 vars in 719 bytes} [Sat Jun 23 06:47:18 2018] GET /static/img/favicon_.png => generated 892 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 8 headers in 287 bytes (1 switches on core 1)
[pid: 2117|app: 0|req: 11/11] 50.82.183.122 () {42 vars in 713 bytes} [Sat Jun 23 06:47:28 2018] GET /static/img/1/Pangestoe-5.jpg => generated 9524805 bytes in 37 msecs via sendfile() (HTTP/1.1 200) 8 headers in 300 bytes (90 switches on core 2)
[pid: 2117|app: 0|req: 12/12] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:47:35 2018] GET /static/img/1/Pangestoe-57.jpg => generated 7535080 bytes in 36 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (76 switches on core 3)
[pid: 2117|app: 0|req: 13/13] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:47:37 2018] GET /static/img/1/Pangestoe-58.jpg => generated 4727330 bytes in 27 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (48 switches on core 4)
[pid: 2117|app: 0|req: 14/14] 50.82.183.122 () {42 vars in 711 bytes} [Sat Jun 23 06:47:38 2018] GET /static/img/bg.gif => generated 397218 bytes in 5 msecs via sendfile() (HTTP/1.1 200) 8 headers in 292 bytes (3 switches on core 5)
[pid: 2117|app: 0|req: 15/15] 50.82.183.122 () {42 vars in 735 bytes} [Sat Jun 23 06:47:39 2018] GET /static/img/1/Pangestoe-33.jpg => generated 12325948 bytes in 52 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (127 switches on core 0)
[pid: 2117|app: 0|req: 16/16] 50.82.183.122 () {42 vars in 735 bytes} [Sat Jun 23 06:47:42 2018] GET /static/img/2/Pangestoe-51.jpg => generated 8138679 bytes in 51 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (84 switches on core 6)
[pid: 2117|app: 0|req: 17/17] 50.82.183.122 () {42 vars in 735 bytes} [Sat Jun 23 06:47:54 2018] GET /static/img/2/Pangestoe-16.jpg => generated 9028953 bytes in 33 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (92 switches on core 7)
[pid: 2117|app: 0|req: 18/18] 50.82.183.122 () {40 vars in 659 bytes} [Sat Jun 23 06:48:11 2018] GET /static/img/favicon_.png => generated 892 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 8 headers in 287 bytes (1 switches on core 1)
[pid: 2117|app: 0|req: 19/19] 91.250.46.186 () {26 vars in 277 bytes} [Sat Jun 23 06:48:14 2018] GET / => generated 6794 bytes in 8 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 2)
[pid: 2117|app: 0|req: 20/20] 50.82.183.122 () {44 vars in 739 bytes} [Sat Jun 23 06:48:14 2018] GET / => generated 6794 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 3)
[pid: 2117|app: 0|req: 21/21] 50.82.183.122 () {44 vars in 743 bytes} [Sat Jun 23 06:48:14 2018] GET /static/css/style.css => generated 2242 bytes in 2 msecs via sendfile() (HTTP/1.1 200) 8 headers in 303 bytes (0 switches on core 4)
[pid: 2113|app: 0|req: 1/22] 50.82.183.122 () {44 vars in 747 bytes} [Sat Jun 23 06:48:14 2018] GET /static/css/gallery.css => generated 2479 bytes in 24 msecs via sendfile() (HTTP/1.1 200) 10 headers in 418 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
[pid: 2117|app: 0|req: 25/23] 50.82.183.122 () {42 vars in 713 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-5.jpg => generated 9524805 bytes in 27 msecs via sendfile() (HTTP/1.1 200) 8 headers in 300 bytes (105 switches on core 7)
[pid: 2117|app: 0|req: 26/24] 50.82.183.122 () {42 vars in 713 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-3.jpg => generated 5570240 bytes in 46 msecs via sendfile() (HTTP/1.1 200) 8 headers in 296 bytes (61 switches on core 6)
[pid: 2117|app: 0|req: 27/25] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-38.jpg => generated 7400066 bytes in 73 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (77 switches on core 5)
[pid: 2117|app: 0|req: 27/26] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-32.jpg => generated 15247103 bytes in 102 msecs via sendfile() (HTTP/1.1 200) 8 headers in 297 bytes (168 switches on core 0)
[pid: 2117|app: 0|req: 27/27] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-57.jpg => generated 7535080 bytes in 86 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (84 switches on core 1)
[pid: 2117|app: 0|req: 27/28] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:48:15 2018] GET /static/img/1/Pangestoe-35.jpg => generated 8184620 bytes in 88 msecs via sendfile() (HTTP/1.1 200) 8 headers in 294 bytes (90 switches on core 2)
[pid: 2117|app: 0|req: 28/29] 50.82.183.122 () {48 vars in 878 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/1/Pangestoe-33.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 209 bytes (1 switches on core 3)
[pid: 2117|app: 0|req: 30/30] 50.82.183.122 () {48 vars in 877 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/2/Pangestoe-51.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 208 bytes (1 switches on core 7)
[pid: 2117|app: 0|req: 30/31] 50.82.183.122 () {42 vars in 715 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/1/Pangestoe-58.jpg => generated 4727330 bytes in 17 msecs via sendfile() (HTTP/1.1 200) 8 headers in 295 bytes (52 switches on core 4)
[pid: 2117|app: 0|req: 31/32] 50.82.183.122 () {48 vars in 877 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/2/Pangestoe-16.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 208 bytes (1 switches on core 6)
[pid: 2117|app: 0|req: 33/33] 50.82.183.122 () {48 vars in 852 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/bg.gif => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 207 bytes (1 switches on core 0)
[pid: 2117|app: 0|req: 33/34] 50.82.183.122 () {48 vars in 862 bytes} [Sat Jun 23 06:48:21 2018] GET /static/img/logo_placeholder.png => generated 0 bytes in 7 msecs (HTTP/1.1 304) 5 headers in 209 bytes (0 switches on core 5)
[pid: 2117|app: 0|req: 34/35] 50.82.183.122 () {48 vars in 856 bytes} [Sat Jun 23 06:48:22 2018] GET /static/img/1/Pangestoe-2.jpg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 5 headers in 209 bytes (1 switches on core 1)
